[package]
name = "clap_builder"
version = "4.6.6"
description = "A simple to use, efficient, and full-featured Command Line Argument Parser"
categories = ["command-line-interface"]
keywords = [
  "argument",
  "cli",
  "arg",
  "parser",
  "parse"
]
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
include.workspace = true

[package.metadata.docs.rs]
features = ["wrap_help"]
rustdoc-args = ["--generate-link-to-definition"]

[package.metadata.playground]
features = ["wrap_help"]

[package.metadata.release]
shared-version = true
dependent-version = "upgrade"
tag-name = "v{{version}}"

[features]
default = ["std", "color", "help", "usage", "error-context", "suggestions"]
debug = ["dep:backtrace"] # Enables debug messages

# Used in default
std = ["anstyle/std"] # support for no_std in a backwards-compatible way
color = ["dep:anstream"]
help = []
usage = []
error-context = []
suggestions = ["dep:strsim", "error-context"]

# Optional
wrap_help = ["help", "dep:terminal_size"]

[lib]
bench = false

[dependencies]
clap_lex = { path = "../clap_lex", version = "1.0.0" }
strsim = { version = "0.11.1",  optional = true }
anstream = { version = "1.0.0", optional = true }
anstyle = "1.0.14"
terminal_size = { version = "0.4.4", optional = true }
backtrace = { version = "0.3.76", optional = true }

[dev-dependencies]
static_assertions = "1.1.0"
color-print = "0.3.7"
snapbox = { version = "1.2.0" }

[lints]
workspace = true
